spring:
  datasource:
    url: jdbc:mysql://mysql:3306/health_ai_hub?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: redis
      database: 0
      port: 6379
      password: ${REDIS_PASSWORD:114514}
      timeout: 3000ms
    mongodb:
      uri: mongodb://mongo:27017/health_ai_hub
  ai:
    zhipuai:
      api-key: ${API_KEY}
      chat:
        options:
          model: GLM-4-Flash
          temperature: 0.7
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:114514}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

minio:
  endpoint: http://minio:9000
  external-endpoint: http://localhost:9000
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: health

knife4j:
  production: true

logging:
  file:
    path: /var/log/app